name: build action
on:
  push: 
    branches: [main]
jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Run #${{ github.run_number }}"
        echo "By ${{ github.actor }}"
        echo "Branch ${{ github.ref_name }}"

